name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pdflatex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Run build script
        run: ./scripts/build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Generated PDFs
          path: temp/*.pdf
