name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pdflatex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Run build script
        run: ./scripts/build

      - name: Upload PDFs to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "temp/*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          name: "Generated PDFs"
          body: "Updated PDFs in the release"
